name: mvvm
description: MVVM for Flutter. 
version: 0.1.0
author: yichen <d.unicreators@gmail.com>
homepage: https://github.com/unicreators/mvvm
repository: https://github.com/unicreators/mvvm

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
